name: linter-units

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - run: poetry install

      - name: Run flake8
        run: make lint

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: 6bd58fc82e14ee77b1e2bdfd3afbce42c1e23d5b7ef4572d4db9ac8896fce2f1
        with:
          coverageCommand: make run-tests
          debug: true